services:
  postgres:
    image: postgres:15
    container_name: medicloud_postgres
    environment:
      POSTGRES_USER:     medicloud
      POSTGRES_PASSWORD: medicloud123
      POSTGRES_DB:       medicloud_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medicloud_backend
    environment:
      DATABASE_URL: postgresql://medicloud:medicloud123@postgres:5432/medicloud_db
      RAZORPAY_KEY_ID:     rzp_test_SYuRjpqkkJl1rB
      RAZORPAY_KEY_SECRET: 4IAvT31k1TS4H6DWvQaE8o3X
      ABDM_BASE_URL:       https://dev.abdm.gov.in
      ABDM_CLIENT_ID:      SBXID_047494
      ABDM_CLIENT_SECRET:  b3d9be4b-4507-4231-8ef7-5acd01d10b12
      ABDM_CM_ID:          sbx
      ABDM_HIP_ID:         ""
    ports:
      - "8001:8000"
    volumes:
      - report_assets_data:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medicloud_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  report_assets_data:
